# Generated by Django 4.0.5 on 2022-06-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=1500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupants_count', models.IntegerField(blank=True, default=0, null=True)),
                ('police_num', models.IntegerField(max_length=255)),
                ('hospital_num', models.IntegerField(max_length=255)),
                ('locattion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locattion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.location')),
            ],
        ),
    ]
