# Generated by Django 4.0.5 on 2022-06-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0002_category_rename_locattion_business_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Hood_update',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='locattion',
            new_name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, default='business.jpg', upload_to='bizimages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighbourhood'),
        ),
    ]
