# Generated by Django 4.0.5 on 2022-06-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_rename_post_hood_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='neighbourhood',
        ),
    ]
