# Generated by Django 4.0.5 on 2022-06-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
    ]
