# Generated by Django 4.0.5 on 2022-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0006_remove_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hospital_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
