# Generated by Django 4.0.5 on 2022-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0007_alter_neighbourhood_hospital_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood_update',
            name='image',
            field=models.ImageField(blank=True, default='business.jpg', upload_to='bizimages'),
        ),
    ]
