# Generated by Django 4.0.5 on 2022-06-19 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0008_hood_update_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
